### PR TITLE
 Add support for fetch_max/fetch_min on simt::atomic type 

### PR DESCRIPTION
**Pull request by igelado**
This request fixed the compilation issues my previous request had

### CODE REVIEW

**Comment by ogiroux** [comment]
The code generator needs to be updated to emit the "builtins" instead hand-editing them into the generated file. Also, there needs to be a host definition under #ifdef __CUDA_ARCH__, the simt:: namespace functions are heterogeneous.

**Comment by igelado** [comment]
Please, check if the last commit fixes those issues

**Comment by ogiroux** [comment]
The codegen change looks good. Note, you accidentally committed the executable build product!

The __atomic_derived change has one problem I missed earlier, and one new surprise that is probably not a problem:

- The problem is that you're missing the reevaluation of the min/max expression inside of the CAS loop when you see a new value in memory. Also, your optimization branch probably should be "if(desired != expected)" to save some performance when val == expected.

- The surprise is that you implemented the host path in __atomic_derived instead of in simt/atomic directly, where I expected it to be (in terms of this->compare_exchange_...). Prior to this, __atomic_derived didn't introduce any host symbols so you could read that file as a device only file.

After fixing the one problem and removing the binary file, you should be good.

**Comment by igelado** [comment]
Binary file removed and fixed the re-evaluation problem. Bonus commit: added a .gitignore to the util directory to make it harder to accidentally push the codegen binary.

At first I actually implemented it as you were expecting, but that would mean duplicating the `compare_exchange` loop in two different places.

**Pull request merged**
